Task 1

Creating matrices A and B

In [1]:
import cupy as cp
rand_A =  cp.random.randint(100,size = (1500,1500))
rand_B = cp.random.randint(100,size = (1500,1500))

print('Matrix A: ', rand_A, '\n')
print('Matrix B: ', rand_B, '\n')

Matrix A:  [[61 61 49 ...  4 41 94]
 [25 78 49 ... 90 76 12]
 [71 67 62 ... 24 57 70]
 ...
 [53  2 22 ... 10 79 15]
 [99 43 72 ... 50  4 57]
 [36 90  9 ...  2 36 63]] 

Matrix B:  [[27 13 39 ... 31 62 96]
 [56 10 38 ... 76 42 42]
 [26  2 77 ... 80 95 90]
 ...
 [24 63 38 ... 85 72 11]
 [39 25 13 ... 73 91 80]
 [24 14 84 ... 36 14 98]] 



За да докажем, че равенството - $(AB)^{-1} = B^{-1}A^{-1}$ е вярно , то трябва да намерим детерминантата на дадените матрици и те трябва да са ≠ от 0;
тогава матриците могат да бъдат обратими и може да продължим с решението.

In [2]:
dA = cp.linalg.det(rand_A)
dB = cp.linalg.det(rand_B)
print(dA)
print(dB)

inf
-inf


Получаваме детерминантите на двете матрици, ако са различни от 0, обръщаме матриците A и B, намираме произведението им baI. Произведението на A и B е ab, след което получената матрица ab е обърната.
Накрая срявняваме двете матрици и получаваме нужния резултат.
Else е случая където някоя от детерминантите на A и B може да е = 0.

In [3]:
if dA != 0 and dB != 0:
    aI = cp.linalg.inv(rand_A)
    bI = cp.linalg.inv(rand_B)
    baI = cp.dot(bI,aI)
    ab = cp.dot(rand_A,rand_B)
    ab = cp.linalg.inv(ab)
    res = cp.allclose(ab,baI)
    print('Are the equations equal : ', res)
else: pass


Are the equations equal :  True


Разглеждаме : $(A^T)^{-1}=(A^{-1})^T$

In [4]:
if dA != 0:
    aT = cp.transpose(rand_A)
    atI = cp.linalg.inv(aT)
    Ai = cp.linalg.inv(rand_A)
    At = cp.transpose(Ai)
    r = cp.allclose(atI,At)
    print('Are the equations equal : ', r)
else: pass

Are the equations equal :  True


Разглежадаме : $(\alpha A)^{-1}=(1/\alpha)A^{-1}$,  $\alpha$ е реално число.

In [5]:
alpha = cp.real(cp.random.randint(100))
al1 = 1/alpha
if dA != 0 :
    aAI = cp.linalg.inv(alpha * rand_A)
    ai = cp.linalg.inv(rand_A)
    m = al1 * ai
    rez = cp.allclose(aAI, m)
    print('Are the equations equal : ', rez)
else: pass

Are the equations equal :  True


Numpy


$(AB)^{-1} = B^{-1}A^{-1}$

In [6]:
import numpy as np

rand_A =  np.random.randint(100,size = (1500,1500))
rand_B = np.random.randint(100,size = (1500,1500))
dA = np.linalg.det(rand_A)
dB = np.linalg.det(rand_B)
print(dA)
print(dB)
if dA != 0 and dB != 0:
    aI = np.linalg.inv(rand_A)
    bI = np.linalg.inv(rand_B)
    baI = np.dot(bI,aI)
    ab = np.dot(rand_A,rand_B)
    ab = np.linalg.inv(ab)
    res = np.allclose(ab,baI)
    print('Are the equations equal : ', res)
else: pass

-inf
inf


/home/memi/Desktop/ML_Uni/.venv/lib/python3.10/site-packages/numpy/linalg/linalg.py:2139: RuntimeWarning: overflow encountered in det
  r = _umath_linalg.det(a, signature=signature)


Are the equations equal :  True


$(A^T)^{-1}=(A^{-1})^T$

In [7]:
if dA != 0:
    aT = np.transpose(rand_A)
    atI = np.linalg.inv(aT)
    Ai = np.linalg.inv(rand_A)
    At = np.transpose(Ai)
    r = np.allclose(atI,At)
    print('Are the equations equal : ', r)
else: pass

Are the equations equal :  True


 $(\alpha A)^{-1}=(1/\alpha)A^{-1}$,  $\alpha$ е реално число.

In [8]:
alpha = np.real(np.random.randint(100))
al1 = 1/alpha
if dA != 0 :
    aAI = np.linalg.inv(alpha * rand_A)
    ai = np.linalg.inv(rand_A)
    m = al1 * ai
    rez = np.allclose(aAI, m)
    print('Are the equations equal : ', rez)
else: pass

Are the equations equal :  True
