Разглеждаме квадратичната форма $3x^2 + 8xz + 2y^2 + 6z^2$.

а) съставете съответната й матрица 
имаме $$Q(x,y,z) = (x,y,z) \begin{pmatrix} a_{1,1} &  \cdots & a_{1,n} \\ \vdots & & \vdots \\  a_{n,1} &  \cdots & a_{n,n} \end{pmatrix}  \begin{pmatrix} x \\ y \\z  \end{pmatrix} $$ 
Съставяме матрицата $$ A = \begin{pmatrix} a_{1,1} &  \cdots & a_{1,n} \\ \vdots & & \vdots \\  a_{n,1} &  \cdots & a_{n,n} \end{pmatrix} $$
б) намерете нейните собствени стойности и вектори;

In [1]:
import numpy as np
A = [
        [3, 0, 4],
        [0, 2, 0],
        [4, 0, 6]
    ]

E, v =np.linalg.eig(A)

print('Eigenvalues from matrix A: ', E)
print('Eigenvectors from matrix A: ', v)

Eigenvalues from matrix A:  [0.22799813 8.77200187 2.        ]
Eigenvectors from matrix A:  [[-0.82192562 -0.56959484  0.        ]
 [ 0.          0.          1.        ]
 [ 0.56959484 -0.82192562  0.        ]]


в) какъв тип е матрицата $U$ от собствените й вектори 

Векторите са взаимно ортогонални : 

In [2]:
v1 = v[:,0]
print(v1)

[-0.82192562  0.          0.56959484]


In [3]:
v2 = v[:,1]
print(v2)

[-0.56959484  0.         -0.82192562]


In [4]:
v3 = v[:,2]
print(v3)

[0. 1. 0.]


In [5]:
np.dot(v1,v2)


0.0

In [6]:
np.dot(v1,v3)

0.0

In [7]:
np.dot(v2,v3)

0.0

Матрицата U е ортогонална; имаме матрицата $ U^T . U = I $


I- единичната матрица 

In [8]:
U = np.transpose(np.matrix(v))
print(U)

[[-0.82192562  0.          0.56959484]
 [-0.56959484  0.         -0.82192562]
 [ 0.          1.          0.        ]]


In [9]:
UT = np.transpose(U)
print(UT)

[[-0.82192562 -0.56959484  0.        ]
 [ 0.          0.          1.        ]
 [ 0.56959484 -0.82192562  0.        ]]


In [10]:
UM = np.dot(UT,U)
print(UM)
I = np.identity(3)
np.allclose(UM, I)

[[ 1.00000000e+00  0.00000000e+00 -2.70726788e-17]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-2.70726788e-17  0.00000000e+00  1.00000000e+00]]


True

На какъв тип геометрична операция съответства $U.(x,y,z)^T$ ?


$$\begin{pmatrix} x_1 \\ y_1 \\z_1  \end{pmatrix} = U \cdot \begin{pmatrix} x \\ y \\ z \end{pmatrix} $$ 

$$ \begin{pmatrix} x_1 \\ y_1 \\z_1 \end{pmatrix}^{T} = \left( x_1, y_1, z_1 \right) $$

$$ \left( x_1, y_1, z_1 \right) \cdot \begin{pmatrix} x_1 \\ y_1 \\z_1 \end{pmatrix} = x_1^2 + y_1^2 + z_1^2 $$

$$ \left[ U \cdot \begin{pmatrix} x \\ y \\ z  \end{pmatrix} \right] ^{T} \cdot \left[ U . \begin{pmatrix} x \\ y \\ z  \end{pmatrix} \right] = $$

$$ \begin{pmatrix} x \\ y \\ z \end{pmatrix}^{T} \cdot U^T \cdot U \cdot \begin{pmatrix} x \\ y \\ z \end{pmatrix} = $$

$$\begin{pmatrix} x \\ y \\ z \end{pmatrix} \cdot \begin{pmatrix} x \\ y \\ z \end{pmatrix} = x^2 + y^2 + z^2 $$ 

$$ U^T \cdot U = I $$ 
 I e единичната матрица
  
 ОТГ: от това следва че се запазват дължините на векторите



2*. Ако матрицата, свързана с дадена квадратична форма, има само положителни собствени стойности (, както е в горния случай), то какво свойство на квадратичната форма можете да посочите? 


ОТГ: При положителни собствени стойности, можем да твърдим, че квадратичната форма е положително определена