Задача 1
-  изчислете "на ръка" и чрез PyTorch стойностите на невроните $z_i^{(j)}$, като и стойностите на производните $∂_{w_{11}^{(2)}}L,∂_{w_{21}^{(2)}}L,∂_{w_{11}^{(1)}}L$;
- обновете чрез PyTorch един път стойностите на величините по мрежата.

In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
from collections import OrderedDict
model = nn.Sequential(OrderedDict([
    ('lin1', nn.Linear(3, 2)),
    ('sig1', nn.Sigmoid()),
    ('lin2', nn.Linear(2, 2)),
    ('sig2', nn.Sigmoid())]))

In [3]:
model.lin1.weight.data = torch.tensor(np.array([0.1,0.3,0.25,0.2,0.15,0.11]).reshape((2, 3))).float()
model.lin1.bias.data = torch.zeros_like(model.lin1.bias.data).float()
model.lin2.weight.data = torch.tensor(np.array([0.3,0.1,0.2,0.2]).reshape((2, 2))).float()
model.lin2.bias.data = torch.zeros_like(model.lin2.bias.data).float()

In [4]:
x = torch.tensor([0.3, 0.1, 0.5])
a1 = model.lin1(x)
z1 = model.sig1(a1)
y = model(x)
t = torch.tensor([0.5,0.55]).float()

In [5]:
print('Input values: ', x)
print('First layer: ', z1)
print('Output layer: ', y)
print('Target values: ', t)

Input values:  tensor([0.3000, 0.1000, 0.5000])
First layer:  tensor([0.5461, 0.5325], grad_fn=<SigmoidBackward0>)
Output layer:  tensor([0.5541, 0.5537], grad_fn=<SigmoidBackward0>)
Target values:  tensor([0.5000, 0.5500])


In [6]:
loss = nn.MSELoss()
L = loss(y,t)

In [7]:
print(L)

tensor(0.0015, grad_fn=<MseLossBackward0>)


In [8]:
L.backward()

In [9]:
print(model.lin1.weight.grad)
print(model.lin2.weight.grad)

tensor([[3.1164e-04, 1.0388e-04, 5.1940e-04],
        [1.1348e-04, 3.7828e-05, 1.8914e-04]])
tensor([[0.0073, 0.0071],
        [0.0005, 0.0005]])


In [10]:
print(model.lin1.weight)
print(model.lin2.weight)

Parameter containing:
tensor([[0.1000, 0.3000, 0.2500],
        [0.2000, 0.1500, 0.1100]], requires_grad=True)
Parameter containing:
tensor([[0.3000, 0.1000],
        [0.2000, 0.2000]], requires_grad=True)


In [11]:
optimizer = optim.SGD(model.parameters(), lr = 0.01)

In [12]:
optimizer.step()

In [14]:
print(model.lin1.weight)
print(model.lin2.weight)

Parameter containing:
tensor([[0.1000, 0.3000, 0.2500],
        [0.2000, 0.1500, 0.1100]], requires_grad=True)
Parameter containing:
tensor([[0.2999, 0.0999],
        [0.2000, 0.2000]], requires_grad=True)
